session_name: main
start_directory: $HOME
global_options: {}

windows:

- window_name: btop
  options:
    visual-bell: off
    monitor-activity: off
  panes:
  - shell: /usr/bin/btop

- window_name: logs
  options:
    visual-bell: off
    monitor-activity: off
  layout: be21,239x57,0,0[239x20,0,0,2,239x36,0,21,17]
  panes:
  - shell: /usr/bin/grc -es journalctl -f
  - shell: /usr/bin/multitail -cT ansi $HOME/var/log/*.log

- window_name: wtf
  options:
    visual-bell: off
    monitor-activity: off
  panes:
  - shell: /usr/local/bin/wtfutil

- window_name: apps
  layout: tiled
  options:
    visual-bell: off
    monitor-activity: off
  panes:
    - shell: /usr/bin/slrn -w0
      focus: true
    - shell: /usr/bin/slrn -w0 -f .jnewsrc.tilde -h snews://news.tilde.club
    - shell: weechat

    - shell: mutt
    - shell: /usr/bin/newsboat
    - shell: /usr/local/bin/hackernews_tui

    - shell:
    - shell: $HOME/bin/ticker
    - shell: /usr/bin/cointop --only-table

- window_name: bash
  focus: true
  panes:
    - null
