session_name: main
start_directory: $HOME
global_options: {}

windows:

- window_name: btop
  options:
    visual-bell: off
    monitor-activity: off
  panes:
  - shell: /usr/bin/btop

- window_name: logs
  options:
    visual-bell: off
    monitor-activity: off
  panes:
  - shell: /usr/bin/grc -es journalctl -f

- window_name: wtf
  options:
    visual-bell: off
    monitor-activity: off
  panes:
  - shell: /usr/local/bin/wtfutil

- window_name: apps
  layout: tiled
  options:
    visual-bell: off
    monitor-activity: off
  panes:
    - shell: /usr/bin/slrn -w0
      focus: true
    - shell: /usr/bin/slrn -w0 -f .jnewsrc.tilde -h snews://news.tilde.club
    - shell: weechat

    - shell: mutt
    - shell: /usr/bin/newsboat
    - shell: /usr/local/bin/hackernews_tui

    - shell:
    - shell: $HOME/bin/ticker
    - shell: /usr/bin/cointop --only-table

- window_name: bash
  focus: true
  panes:
    - null
