session_name: main
start_directory: $HOME
global_options: {}

windows:

- window_name: btop
  options:
    visual-bell: off
    monitor-activity: off
  panes:
    - shell_command:
      - tmux select-pane -T btop -t btop.1
      - /usr/bin/btop

- window_name: logs
  options:
    visual-bell: off
    monitor-activity: off
  layout: be21,239x57,0,0[239x20,0,0,2,239x36,0,21,17]
  panes:
    - shell_command:
      - tmux select-pane -T journalctl -t logs.1
      - /usr/bin/grc -es journalctl -f
    - shell_command:
      - tmux select-pane -T logs -t logs.2
      - /usr/bin/multitail -cT ansi $HOME/var/log/*.log

- window_name: wtf
  options:
    visual-bell: off
    monitor-activity: off
  panes:
    - shell_command:
      - tmux select-pane -T wtf -t wtf.1
      - /usr/local/bin/wtfutil

- window_name: apps
  layout: tiled
  options:
    visual-bell: off
    monitor-activity: off
  panes:
    - shell_command:
      - tmux select-pane -T usenet -t apps.1
      - /usr/bin/slrn -w0
      focus: true
    - shell_command:
      - tmux select-pane -T tilde -t apps.2
      - /usr/bin/slrn -w0 -f .jnewsrc.tilde -h snews://news.tilde.club
    - shell_command:
      - tmux select-pane -T irc -t apps.3
      - weechat

    - shell_command:
      - tmux select-pane -T mail -t apps.4
      - mutt
    - shell_command:
      - tmux select-pane -T rss -t apps.5
      - /usr/bin/newsboat
    - shell_command:
      - tmux select-pane -T hackernews -t apps.6
      - /usr/local/bin/hackernews_tui

    - shell_command:
      - tmux select-pane -T music -t apps.7
      - ncmpcpp
    - shell_command:
      - tmux select-pane -T stocks -t apps.8
      - $HOME/bin/ticker
    - shell_command:
      - tmux select-pane -T crypto -t apps.9
      - /usr/bin/cointop --only-table

- window_name: bash
  focus: true
  panes:
    - null
