#!/bin/sh
#
# Jeremy Brubaker <jbru362@gmail.com>

# Color flag for ls and grep
test "$( tput colors )" -ge 0 && color_flag='--color=auto'
test -n "$color_flag" && LS_COLOR_ALWAYS='--color=always'

# My standard ls aliases {{{1
#
if command -v exa >/dev/null; then
    LS_OPTS="--group-directories-first --sort extension"
    alias ls="command  exa $color_flag $LS_OPTS --classify"
    alias la="command  exa $color_flag $LS_OPTS -a --classify"
    alias ll="command  exa $color_flag $LS_OPTS -lg --icons"
    alias lal="command exa $color_flag $LS_OPTS -lag --icons"
    alias l.="command  exa $color_flag $LS_OPTS --classify -d .*"
    alias lsap="lsp -lA --icons" # lsp is a function defined in ~/.functions

else
    LS_OPTS="--group-directories-first -XF --dereference-command-line-symlink-to-dir"
    alias ls="command  ls $color_flag $LS_OPTS"
    alias la="command  ls $color_flag $LS_OPTS -A"
    alias ll="command  ls $color_flag $LS_OPTS -lh"
    alias lal="command ls $color_flag $LS_OPTS -lhA"
    alias l.="command  ls $color_flag $LS_OPTS -d .*"
    alias lsap="lsp -lA" # lsp is a function defined in ~/.functions
fi

# Force color in *grep {{{1
#
alias grep="grep $color_flag"
unset color_flag

# Easier navigation {{{1
alias ..="cd .."
alias ...="cd ../.."
if test -n "$BASH"; then
    alias -- -="cd -"
else
    alias -="cd -"
fi

# OS specific aliases {{{1
#
case $(uname -o) in
    *)
        ;;
esac

# Alternatives {{{1
alias term='( $(my terminal)& )'
alias calc='( $(my calculator)& )'
alias calendar='( $(my calendar)& )'

# GRC Highlighting {{{1

if command -v grc >/dev/null; then
    df='grc df'
    alias du='grc du'
    alias dig='grc dig'
    alias dnf='grc dnf'
    alias env='grc env'
    alias free='grc free'
    alias id='grc id'
    alias jobs='grc jobs'
    alias last='grc last'
    alias mount='grc mount'
    alias mtr='grc mtr'
    alias netstat='grc netstat'
    alias nmap='grc nmap'
    alias ping='grc ping'
    alias ps='grc ps'
    alias pv='grc pv'
    alias sensors='grc sensors'
    alias ss='grc ss'
    alias stat='grc stat'
    alias sysctl='grc sysctl'
    alias systemctl='grc systemctl'
    alias tcpdump='grc tcpdump'
    alias traceroute='grc traceroute'
    alias uptime='grc uptime'
    alias vmstat='grc vmstat'
    alias whois='grc whois'
fi

# Flatpak aliases {{{1
#
alias lagrange='flatpak run fi.skyjake.Lagrange'
alias signal='flatpak run org.signal.Signal'

# Cassowary {{{1
#
if command -v cassowary >/dev/null 2>&1; then
    alias word='cassowary -c guest-run winword'
    alias excel='cassowary -c guest-run excel'
    alias ppt='cassowary -c guest-run powerpnt'
    alias pub='cassowary -c guest-run mspub'
    alias onenote='cassowary -c guest-run onenote'
    alias access='cassowary -c guest-run msaccess'
fi

# Miscellaneous {{{1
#
# Emulate clear(1) if I don't have it
command -v clear >/dev/null || alias clear='echo -en "\e[2J\e[H"'

# If todo.txt is installed, make it simpler to access
command -v todo.sh >/dev/null && alias t=todo.sh

# If my pager is not less, make me think it is
test "x$PAGER" != 'xless' && alias less="$PAGER" && alias zless="$PAGER"

# Get my real IP
#
if command -v wget >/dev/null; then
    alias myip='wget http://ipecho.net/plain -O - -q; echo'
elif command -v curl >/dev/null; then
    alias myip='curl http://ipecho.net/plain; echo'
else
    alias myip='printf "wget or curl not available\n"'
fi


alias ':q'=exit                                           # Exit like it's vim
alias +x='chmod +x "$@"'                                  # Make file executable
alias -- -x='chmod -x "$@"'                               # Make file non-executable
alias bell='printf "\a"'                                  # Ring the bell
alias df='df -hT'                                         # Make df output nicer
alias dut='du -h --max-depth=1'                           # du(1) prints totals for one level down
alias gist="vim '+Gist -l'"                               # Open Gist browser
alias jobs='jobs -l'                                      # List PID
alias klsshd="kill -TERM \$(cat $HOME/var/run/sshd.pid)"  # Stop user sshd
alias loc='locate -d "$LOCATEDB" "$@"'                    # Use my personal locate(1) db
alias lsshd="/usr/sbin/sshd -f $HOME/etc/ssh/sshd_config" # Start user sshd
alias nu="who | cut -d' ' -f1 | uniq | wc -l"             # Get number of logged on users
command -v reset >/dev/null ||  alias reset='tput sgr0'   # Reset terminal
alias rpg=rpg-cli                                         # rpg-cli but shorter
alias sudo='sudo '                                        # Enable aliases to be sudo’ed
alias tree='command tree -CFI '.git' --dirsfirst'         # Better looking tree(1)
alias unexec="find . -type f -exec chmod ogu-x '{}' \;"   # chmod -x ALL files in tree

command -v reset >/dev/null || \
    alias reset='tput sgr0'          # Reset terminal

# vim: foldlevel=0

