#!/bin/sh vim: foldlevel=0
#
# Jeremy Brubaker <jbru362@gmail.com>
#
# Some stuff ripped from Ryan Tomayko <tomayko.com/about>

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

. "$HOME/.functions"
. "$HOME/.alias"
. "$HOME/.prompts"

if command -v zoxide >/dev/null; then
    export _ZO_DATA_DIR=$XDG_STATE_HOME
    if test -n "$BASH"; then
        eval "$(zoxide init bash --hook pwd)"
    else
        eval "$(zoxide init posix --hook prompt)"
    fi
fi

# FIXME: Launching a terminal from sxhkd starts in /
cd $HOME

