#!/bin/sh
#
# Source - https://stackoverflow.com/a/3464399
# Posted by Cascabel, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-09, License - CC BY-SA 4.0
#
. "$(git --exec-path)/git-sh-setup"

HOOK_NAMES="
    applypatch-msg
    pre-applypatch
    post-applypatch
    pre-commit
    prepare-commit-msg
    commit-msg
    post-commit
    pre-rebase
    post-checkout
    post-merge
    pre-receive
    update
    post-receive
    post-update
    pre-auto-gc"

# Find the relative path from the hooks directory to the tracked hooks
# This makes two assumptions so that it works with worktrees:
#   1. There is a 'main' or 'master' branch
#   2. That branch always has the latest version of tracked hooks
#
HOOK_DIR=$(git rev-parse --path-format=absolute --git-path hooks)
MAIN_WORKTREE=$(git worktree list --porcelain | grep -EB2 'worktree .*/(main|master)$' | head -1 | cut -d' ' -f2)
TRACKED_HOOK_DIR=$MAIN_WORKTREE/.tracked-hooks
HOOK_WRAPPER=$(realpath -m --relative-to="$HOOK_DIR" "$TRACKED_HOOK_DIR")/hook-wrapper

for hook in $HOOK_NAMES; do
    # If the hook already exists and is not a symlink
    if [ -f "$HOOK_DIR/$hook" -a ! -h "$HOOK_DIR/$hook" ]; then
        mv "$HOOK_DIR/$hook" "$HOOK_DIR/$hook.local"
    fi

    # If there is a tracked hook, create the symlink, overwriting the file if it
    # exists.
    #
    # Probably the only way this would happen is if you're using an old version
    # of git -- back when the sample hooks were not executable, instead of being
    # named ____.sample
    [ -f "$TRACKED_HOOK_DIR/$hook" ] && ln -sf "$HOOK_WRAPPER" "$HOOK_DIR/$hook"
done

true

