PREFIX=/usr/share/games

all:
	
install:
	install -m644 chapterhouse-dune $PREFIX/fortunes
	install -m644 children-of-dune $PREFIX/fortunes
	install -m644 dune $PREFIX/fortunes
	install -m644 dune-messiah $PREFIX/fortunes
	install -m644 god-emperor $PREFIX/fortunes
	install -m644 heretics-of-dune $PREFIX/fortunes
	install -m644 house-atreides $PREFIX/fortunes
	install -m644 house-harkonnen $PREFIX/fortunes
	install -m644 chapterhouse-dune.dat $PREFIX/fortunes
	install -m644 children-of-dune.dat $PREFIX/fortunes
	install -m644 dune.dat $PREFIX/fortunes
	install -m644 dune-messiah.dat $PREFIX/fortunes
	install -m644 god-emperor.dat $PREFIX/fortunes
	install -m644 heretics-of-dune.dat $PREFIX/fortunes
	install -m644 house-atreides.dat $PREFIX/fortunes
	install -m644 house-harkonnen.dat $PREFIX/fortunes
	install -m644 calvin $PREFIX/fortunes
	install -m644 calvin.dat $PREFIX/fortunes
	install -m644 kernelcookies $PREFIX/fortunes
	install -m644 kernelcookies.dat $PREFIX/fortunes
	install -m644 osfortune $PREFIX/fortunes
	install -m644 osfortune.dat $PREFIX/fortunes
	install -m644 SP $PREFIX/fortunes
	install -m644 SP.dat $PREFIX/fortunes
	install -m644 starwars $PREFIX/fortunes
	install -m644 starwars.dat $PREFIX/fortunes
