#!/bin/sh
#
# Source - https://stackoverflow.com/a/3464399
# Posted by Cascabel, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-09, License - CC BY-SA 4.0
#
. "$(git --exec-path)/git-sh-setup"

HOOK_NAMES="
    applypatch-msg
    pre-applypatch
    post-applypatch
    pre-commit
    prepare-commit-msg
    commit-msg
    post-commit
    pre-rebase
    post-checkout
    post-merge
    pre-receive
    update
    post-receive
    post-update
    pre-auto-gc"

HOOK_DIR=$GIT_DIR/hooks
TRACKED_HOOK_DIR=.tracked-hooks
HOOK_WRAPPER=../../$TRACKED_HOOK_DIR/hook-wrapper

for hook in $HOOK_NAMES; do
    # If the hook already exists and is not a symlink
    if [ -f "$HOOK_DIR/$hook" -a ! -h "$HOOK_DIR/$hook" ]; then
        mv "$HOOK_DIR/$hook" "$HOOK_DIR/$hook.local"
    fi

    # If there is a tracked hook, create the symlink, overwriting the file if it
    # exists.
    #
    # Probably the only way this would happen is if you're using an old version
    # of git -- back when the sample hooks were not executable, instead of being
    # named ____.sample
    [ -f "$TRACKED_HOOK_DIR/$hook" ] && ln -sf "$HOOK_WRAPPER" "$HOOK_DIR/$hook"
done

true

