#!/bin/sh

internal=eDP-1
hdmi=HDMI-1
dp=DP-1

left=$dp
right=$hdmi

# Get connected screens
screens=$(xrandr -q | grep ' connected' | cut -d' ' -f1)

# How many external monitors are connected?
num_external=$(echo "$screens" | grep -cv "$internal")
screens=$(echo "$screens" | grep -v "$internal")

case $num_external in
    2) xrandr --output "$left" --left-of "$right" --primary --scale 1x1 \
              --output "$right" --scale 1x1 \
              --output "$internal" --off
       ;;
    1) 
        case $1 in
            mirror)
                res_ext=$(xrandr | awk "/^$screens/ {f = 1} /\*/ && f == 1 {print $1; exit}")
                res_int=$(xrandr | awk "/^$internal/ {f = 1} /\+/ && f == 1 {print $1; exit}")

                x_ext=$(echo "$res_ext" | cut -d x -f1)
                y_ext=$(echo "$res_ext" | cut -d x -f2)

                x_int=$(echo "$res_int" | cut -d x -f1)
                y_int=$(echo "$res_int" | cut -d x -f2)

                scale_x=$((x_int / x_ext))
                scale_y=$((y_int / y_ext))

                xrandr --output "$internal" \
                       --output "$screens" --same-as "$internal" --scale "${scale_x}x${scale_y}"
                ;;
            right)
                xrandr --output "$internal" --left-of "$screens" --primary --scale 1x1 \
                       --output "$screens"
                ;;
            left|*)
                xrandr --output "$screens" --left-of "$internal" --primary --scale 1x1 \
                       --output "$internal" --auto
                ;;
        esac
        ;;
    0)
        xrandr --output "$internal" --primary
        ;;
esac

