#!/bin/sh

# Just in case
command -v my >/dev/null || my() { echo xterm; }

command -v keychain >/dev/null || exit 1

eval "$(keychain --eval --nogui --agents ssh,gpg)"

# X requires running a terminal
[ -n "$DISPLAY" ] && t="$(my -v terminal) -e"

# Find all SSH public keys and add the corresponding private key
#
# Using basename to remove the extension doesn't work because keychain
# cannot find the key without the entire path
# The --confhost option to keychain is supposed to use IdentityFile
# to find the key path but I cannot get that to work
$t keychain --quiet --nogui --ignore-missing \
    "$(find "$HOME/.ssh" -name '*.pub' | rev | cut -f 2- -d. | rev)"

