#!/bin/sh

# -layout us                          : US keyboard
# -variant altgr-intl                 : enable 3rd level symbols
# -option                             : clear options
# -option keypad:pointerkeys          : enable mousekeys
# -option shift:both_caps_lock_cancel : L_Shift+R_Shift = CapsLock; any Shift cancels
# -option compose:rctrl               : R_Ctrl = Compose
# -option ctrl:nocaps                 : CapsLock = L_Ctrl
setxkbmap -layout us -variant altgr-intl \
    -option \
    -option keypad:pointerkeys \
    -option shift:both_capslock_cancel \
    -option compose:rctrl \
    -option ctrl:nocaps

# Keep xmodmap stuff here so all the keyboard
# configuration is in a single file

# 37 (Left Ctrl) = ISO_level3_Shift
# 108 (Right Alt) = Left Alt
#
xmodmap -e "clear lock"
xmodmap -e "clear control"
xmodmap -e "clear mod1"
xmodmap -e "clear mod2"
xmodmap -e "clear mod3"
xmodmap -e "clear mod4"
xmodmap -e "clear mod5"
xmodmap -e "keycode 37 = ISO_Level3_Shift"
xmodmap -e "keycode 108 = Alt_L"
xmodmap -e "add control = Control_L"
xmodmap -e "add mod1 = Alt_L Meta_L"
xmodmap -e "add mod2 = Num_Lock"
xmodmap -e "add mod4 = Super_L Super_R"
xmodmap -e "keycode 207 = Hyper_L"

if command -v xcape >/dev/null; then
    # Control_L = Escape by itself
    # Super_*   = Hyper_L by itself
    xcape -e 'Control_L=Escape;Super_L=Hyper_L;Super_R=Hyper_L'
fi

if command -v sxhkd >/dev/null; then
    # Start sxhkd in $HOME, otherwise everything it
    # starts will start in /
    cd
    exec sxhkd &
fi

# Enable NumLock
command -v xdotool >/dev/null && xdotool key Num_Lock

