#!/bin/sh
#
TPLUG_DIR=$(tmux show-option -gqv @tplug-dir)
RS=

# scroll {{{1
#
# Scroll the cached value
scroll_output() {
    separator=' | '
    prepend=
    append=
    width=30

    OPTIND=1
    while getopts 's:p:a:w:' opt; do
        case $opt in
            s) separator=$OPTARG ;;
            p) prepend=$OPTARG ;;
            a) append=$OPTARG ;;
            w) width=$OPTARG ;;
        esac
    done
    shift $((OPTIND - 1))

    plugin=$1
    full_output=$2
    first=1
    last=

    # Always print at least one character of the actual output
    len=$(printf %s%s "$prepend" "$append" | wc -m)
    if [ "$len" -lt "$width" ]; then
        width=$((width - len - 1))
    else
        width=1
    fi

    # Only scroll if the output is greater than the width
    if [ "$(printf %s "$full_output" | wc -m)" -gt "$width" ]; then
        cache=$(get_cache_fn "$plugin").state

        # If current output is the same as the previous output,
        # get the starting index of the previous output
        if [ -r "$cache" ] && [ "$full_output" = "$(sed -n 1p "$cache")" ]; then
            first=$(sed -n 2p "$cache")
            first=$((first + 1))
        fi

        output=$output$separator

        len=$(printf %s "$output" | wc -m)

        # If $first will overflow length, reset to beginning
        if [ "$first" -gt "$len" ]; then
            first=1

        # If we run out of output, fill the output string with
        # enough characters from the front of the output
        elif [ "$((first + width))" -gt "$len" ]; then
            last=$((first + width - len))
            output=$output$(printf %s "$output" | cut -c1-$last)
        fi

        last=$((first + width - 1))

        printf '%s\n' "$full_output"  > "$cache"
        printf '%s\n' "$first"       >> "$cache"
    fi

    output=$(printf %s "$output" | cut -c$first-$last)

    printf %s%s%s "$prepend" "$output" "$append"
}

# plugin {{{1
#
# @description Execute a plugin and return its (possibly cached) output
#
# @arg $1 str Name of the plugin to load
# @arg $@ ?   Arguments to pass to the plugin
#
# @stdout Plugin output
#
plugin() {
    unset scroll separator width
    OPTIND=1
    while getopts 'sS:w:' opt; do
        case $opt in
            s) scroll=1 ;;
            S) separator=$OPTARG ;;
            w) width=$((OPTARG + 1)) ;;
        esac
    done
    shift $((OPTIND - 1))
    OPTIND=1

    plugin=$1; shift
    [ -f $TPLUG_DIR/plugins/$plugin.tmux ] || return

    . $TPLUG_DIR/plugins/$plugin.tmux

    # # Default interval is 5 minutes
    if [ -z "$INTERVAL" ]; then
        interval=300
    # Minimum interval is tmux's status-interval
    elif [ "$INTERVAL" -lt "$(tmux show-option -gv status-interval)" ]; then
        interval=$(tmux show-option -gv status-interval)
    else
        interval=$INTERVAL
    fi

    output=$(get_value "$plugin" "$interval" "$@")

    # Get prepend and append strings if present
    if printf %s "$output" | grep -q "$RS"; then
        prepend=$(printf %s "$output" | cut -d"$RS" -f2)
        append=$(printf %s "$output" | cut -d"$RS" -f3)
        output=$(printf %s "$output" | cut -d"$RS" -f1)
    else
        unset prepend append
    fi

    # TODO: How to properly use width and scrolling with tmux formatting strings?

    if [ -n "$scroll" ]; then
        scroll_output \
            ${separator:+-s "$separator"} \
            ${width:+-w "$width"} \
            ${prepend:+-p "$prepend" } \
            ${append:+-a "$append" } \
            "$plugin" \
            "$output"

    else
        printf %s "$prepend"

        unset last

        if [ -n "$width" ]; then
            # Always print at least one character of the actual output
            last=1
            len=$(printf %s%s "$prepend" "$append" | wc -m)
            [ "$len" -lt "$width" ] && last=$((width - len - 1))
        fi

        printf %s "$output" | cut -c1-$last
        printf %s "$append"
    fi
}

# Cache functions {{{1
#
# Usage:
#     get_value <command> <interval> <args>
#
#         <command> is the command to run, cache and print. <command> is used as
#         the name of the cache
#         <interval> is the number of seconds until the cache is invalid
#         <args> are passed to <command>
#
#     clear_cache <name>
#         Forcibly clear the cache <name>
#
# Based on the caching function in https://github.com/odedlaz/tmux-status-variables

# Use the tmux socket directory to hold the cache
TPLUG_CACHE=${TMUX_TMPDIR:-/tmp}/tmux-$(id -u)/tplug
[ ! -d "$TPLUG_CACHE" ] && mkdir -p "$TPLUG_CACHE"

# get_value {{{2
#
# @description Get a cached value if available, otherwise get and cache a new value
#
# @arg $1 str command to run if cache is invalid
# @arg $2 int interval in seconds until cache is invalid
# @arg $@ ?   arguments to pass to 
#
# @stdout cached or new value
#
get_value() {
    case $# in
        0) return ;;                           # no plugin to run
        1) plugin=$1; interval=300; shift 1 ;; # use default interval
        *) plugin=$1; interval=$2;  shift 2 ;;
    esac

    delta="$(( $(now) - $(get_cache_time "$plugin") ))"

    if [ "$delta" -lt "$interval" ]; then
        get_cache "$plugin"
    else
        set_cache "$plugin" "$@"
    fi
}

# get_cache {{{2
#
# @description Get a cached value
#
# @arg $1 str cache name
#
# @stdout Cached value
#
get_cache() { head -1 "$(get_cache_fn "$1")"; }

# set_cache {{{2
#
# @description Set and print a cached value
#
# @arg $1 cache name to set
# @arg $2 command to run and cache
#
# @stdout new cached value
#
set_cache() {
    function=$1; shift

    # Split getting function output from tee, otherwise plugin functions
    # cannot read their own cache (which is needed for plugins that need
    # to store additional state in their cache
    out=$("$function" "$@")
    printf %s "$out" | tee "$(get_cache_fn "$function")" | head -1
}

# get_cache_fn {{{2
#
# @description Get the file path of a cache
#
# @arg $1 str Cache name
#
# @stdout Path to cache
#
get_cache_fn() { echo "$TPLUG_CACHE/$1.cache"; }

# get_cache_time {{{2
#
# @desccription Get the time the cache was last updated
#
# @arg $1 cache name
#
# @stdout Time of last update in seconds since the epoch
#
get_cache_time() {
    __cache_fn=$(get_cache_fn "$1")
    if [ -s "$__cache_fn" ]; then
        stat --format %Y "$__cache_fn" 2>/dev/null
    else
        echo "0"
    fi
}

# clear_cache {{{2
#
# @ Clear a cache
#
# @arg $1 str Name of cache to clear
#
clear_cache() { rm -f "$(get_cache_fn "$1")"; }

# Other functions {{{1
#
# now {{{2
#
# @description Print the time in seconds from the epoch
#
# @noarg
#
# @stdout Seconds since the epoch
#
now() {
    echo $(( $(TZ=GMT0 date \
        +"((%Y-1600)*365+(%Y-1600)/4-(%Y-1600)/100+(%Y-1600)/400+1%j-1000-135140) \
        *86400+(1%H-100)*3600+(1%M-100)*60+(1%S-100)") ))
}

# colorize {{{2
#
# Colorize stuff
colorize() {
    [ -n "$TMUX_NOCOLOR" ] && return

    # Discard any decimal
    n=$(echo "$1" | sed 's/\.*$//')

    if [ $n -lt $2 ]; then
        color=${TMUX_COLOR_RED:-red}
    elif [ $n -lt $3 ]; then
        color=${TMUX_COLOR_YELLOW:-yellow}
    else
        color=${TMUX_COLOR_GREEN:-green}
    fi

    printf "#[fg=%s]" "$color"
}

# get_pct {{{2
#
# Get integer percent
get_pct() {
    if [ "$2" = 0 ]; then
        echo 100
    else
        printf '%.0f' "$(echo "$1 / $2 * 100" | bc -l)"
    fi
}

# get_pct_remaining {{{2
#
# Get integer percent remaining
get_pct_remaining() { echo $(( 100 - $(get_pct "$1" "$2") )); }

# Main {{{1
#
# Source status and window definitions
. $TPLUG_DIR/status.sh
# and run one of the functions defined there
"$@"

