#!/bin/sh

[ -z "$DISPLAY" ] && exit

internal=eDP-1

# Get connected screens
screens=$(xrandr -q | grep ' connected' | cut -d' ' -f1)

# How many external monitors are connected?
num_external=$(echo "$screens" | grep -cv "$internal")
screens=$(echo "$screens" | grep -v "$internal")

case $num_external in
    # Two external monitors == home office
    2) 
        left=DP-1-5
        right=DP-1-6 

        xrandr --output "$left" --left-of "$right" --auto --primary --scale 1x1 \
               --output "$right"                   --auto --scale 1x1 \
               --output eDP-1                      --off
    ;;

    # One external monitor
    1) 
        case $1 in
            # External monitor to the right or left of internal screen
            right|left)
            xrandr --output "$screens" --$1-of "$internal" --auto --primary --scale 1x1 \
                   --output "$internal"                    --auto
            ;;
            # External monitor only
            external)
            xrandr --output "$screens" \
                   --output "$internal" --off
            ;;

            mirror|*)
                res_ext=$(xrandr | awk "/^$screens/  {f = 1} /\*/ && f == 1 {print \$1; exit}")
                res_int=$(xrandr | awk "/^$internal/ {f = 1} /\*/ && f == 1 {print \$1; exit}")

                x_ext=$(echo "$res_ext" | cut -d x -f1)
                y_ext=$(echo "$res_ext" | cut -d x -f2)

                x_int=$(echo "$res_int" | cut -d x -f1)
                y_int=$(echo "$res_int" | cut -d x -f2)

                scale_x=$((x_int / x_ext))
                scale_y=$((y_int / y_ext))

                # Failsafe scaling
                if [ "$scale_x" = 0 -a "$scale_y" = 0 ]; then
                    scale=
                else
                    scale="--scale ${scale_x}x${scale_y}"
                fi

                xrandr --output "$internal" \
                       --output "$screens" --same-as "$internal" $scale
                ;;
        esac
        ;;
    0)
        xrandr --output "$internal" --primary
        ;;
esac

