#!/bin/sh

command -v keychain >/dev/null || exit 1

# Don't do anything if we are already done
[ -f "$HOME/.keychain/$(hostname)-sh" ] && exit

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/keychainrc" ] &&
    . "${XDG_CONFIG_HOME:-$HOME/.config}/keychainrc"

[ -n "$KCHOPTS" ] || KCHOPTS='--quiet --agents gpg,ssh'

# Do not prompt to add keys if stdin is not a TTY
[ ! -t 1 ] && KCHOPTS="$KCHOPTS --noask"

# The default is to find all SSH private keys that are
# somewhere under ~/.ssh
#
: ${SSHKEYS:="$(find "$HOME/.ssh" -type f -exec grep -sle '[DRS]S[AH] PRIVATE KEY' {} +)"}

# Because this file is executed in a subshell, your login shell (or DM) need
# to run `eval $(keychain --eval --agents gpg,ssh)`
keychain $KCHOPTS $SSHKEYS $GPGKEYS

unset KCHOPTS SSHKEYS GPGKEYS

