# TODO: Duplicates .env
# Make python use ~/lib instead of ~/.local/lib
PYTHONUSERBASE=$HOME

# TODO: Duplicates .env
XDG_DATA_HOME=$HOME/share
XDG_CACHE_HOME=$HOME/var/cache
XDG_STATE_HOME=$HOME/var/lib

